
--SELECT table_name FROM  user_tables;
--DROP TABLE MyTable;
/*
CREATE TABLE MyTable(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    val NUMBER
);*/

/*
BEGIN
    FOR i IN 1..10000 LOOP
        INSERT INTO MyTable(val) VALUES(TRUNC(DBMS_RANDOM.VALUE(1, 10000)));
        END LOOP;
END;
*/
--SELECT * FROM MyTable;

CREATE OR REPLACE FUNCTION compare_even_odd RETURN VARCHAR IS
    v_even NUMBER;
    v_odd NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_even FROM MYTABLE WHERE MOD(val, 2) = 0;
    SELECT COUNT(*) INTO v_odd FROM MYTABLE WHERE MOD(val, 2) <> 0;
    case
    when v_even > v_odd then
        return 'Even';
    when v_even < v_odd then
        return 'Odd';
    else
        return 'Equal';
    end case;
END;

SELECT compare_even_odd() from dual;

CREATE OR REPLACE FUNCTION generate_insert_command_dynamic (input_id IN NUMBER)
RETURN VARCHAR2 IS
    insert_command VARCHAR2(400);
    val_to_insert NUMBER;
BEGIN

    BEGIN
        SELECT val INTO val_to_insert
        FROM MyTable
        WHERE id = input_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Ошибка: Строка с ID = ' || input_id || ' не найдена!');
            val_to_insert := NULL;
    END;
    insert_command := 'INSERT INTO MyTable(val) VALUES(' || val_to_insert || ');';
    DBMS_OUTPUT.PUT_LINE(insert_command);
    RETURN insert_command;
END generate_insert_command_dynamic;

/
select generate_insert_command_dynamic(30001) from dual;





