DROP USER DEVELOPER CASCADE;
DROP USER PRODUCTION CASCADE;

-- Configure environments
CREATE USER DEVELOPER IDENTIFIED BY developer;
GRANT ALL PRIVILEGES TO DEVELOPER;

CREATE USER PRODUCTION IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO PRODUCTION;

-- we will create test tables here further
